# Generated by Django 5.0 on 2023-12-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enroll_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
