# Generated by Django 5.0 on 2023-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField()),
                ('bill_number', models.PositiveIntegerField()),
                ('paid', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
