# Generated by Django 5.0 on 2023-12-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paidAmount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
