# Generated by Django 5.0 on 2023-12-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
            preserve_default=False,
        ),
    ]
